/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ZarrMetadata = t.iface([], {
  "zarr_format": t.union(t.lit(1), t.lit(2)),
  "shape": t.array("number"),
  "chunks": t.array("number"),
  "dtype": t.union("string", t.array("string")),
  "compressor": t.union("null", t.iface([], {
    "id": "string",
  })),
  "fill_value": t.union("number", t.lit("NaN"), t.lit("Infinity"), t.lit("-Infinity"), "null"),
  "order": t.union(t.lit("C"), t.lit("F")),
  "filters": t.union("null", t.iface([], {
    "id": "string",
  })),
});

export const ZarrGroupMetadata = t.iface([], {
  "zarr_format": t.union(t.lit(1), t.lit(2)),
});

const exportedTypeSuite: t.ITypeSuite = {
  ZarrMetadata,
  ZarrGroupMetadata,
};
export default exportedTypeSuite;
